### ISSUE TITLE
添加媒体文件缓存配置项到配置文件

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#117]
即原版 gocq 配置文件中的这部分内容

```
  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db
```

本插件生成的 config.yml 中似乎没有这部分内容，我手动为多个账号填写进去，指定到同一个份 db 文件，是否可行？
另外如果可行的话能不能增加一个 webui 上的选项直接指定_(:з」∠)_

~~题外话，这个插件实在太牛了，mix，神！~~
